12 factor app
devonfw/devon4node pull request #708
Opened 2022-04-06 05:57 UTC by akanagar

2022-04-07 10:56 UTC, sjimenez77 requested changes
I am not reviewing anymore since it seems that this document is a copy paste from another one from devon4j. Please, check the document to update references to java, spring boot or any java related topic. It is very important to make a first review of your work first before creating a PR .

2022-04-07 10:56 UTC, sjimenez77 commented on documentation/12-factor-app-devon4node.asciidoc
> +This document mainly focuses on discussing how can you create 12 factor app with devon4j. To know more about this 12 factors you can refer https://12factor.net/[here] . Twelve factor is mainly focus
devon4node instead devon4j

2022-04-07 10:56 UTC, sjimenez77 commented on documentation/12-factor-app-devon4node.asciidoc
> += 12-factor-app with devon4j
devon4node instead devon4j

2022-04-07 10:56 UTC, sjimenez77 commented on documentation/12-factor-app-devon4node.asciidoc
> +To create and manage library in spring boot refer https://docs.nestjs.com/cli/libraries[here]  +
Spring Boot? devon4node is based on NestJS

2022-04-07 10:56 UTC, sjimenez77 commented on documentation/12-factor-app-devon4node.asciidoc
> +Here, configuration means anything which can vary between different deployment such as credential to external sources, backing services etc. To do such configuration in your java application refer gu
java application?

2022-04-08 05:30 UTC, closed without merging

2022-04-08 05:30 UTC, akanagar commented
will create new one